/* LATINVM — Fabellae Latinae 22–30 (Ørberg). Uso pessoal. */

FABELLAE.push(...([
 {
  "id": "fab22",
  "cap": 19,
  "icon": "💘",
  "title": "Amor adulēscentium",
  "level": "cap. I–XIX",
  "text": "Iūlius in peristÿlō suō magniﬁcō, quod columnīs et signīs deōrum ōrnātur, cum amīcō suō Cornēliō loquitur. “Certē tū vir beātus es, Iūlī”, inquit Cornēlius, “nam vīllam magniﬁcam possidēs cum magnā familiā atque uxōre pulcherrimā.”\n\nIūlius: “Mea uxor nōn pulchrior est quam tua. Tū quoque es vir beātus, Cornēlī, quamquam tibi nōn tanta vīlla atque minor familia est. Neque enim eae sunt rēs quae hominēs beātōs faciunt.”\n\nAd hoc Cornēlius “Ita est ut dīcis”, inquit, “sed vir pauper ā fēminīs dīvitibus nōn amātur neque virgō pauper amātur ā virīs dīvitibus!”\n\nIūlius: “Immō ego adulēscēns dīves virginem pauperem amābam – nec vērō ab eā amābar!\n\nNumquam ab eā salūtābar, epistulae ac ﬂōrēs, quōs ad eam mittēbam, ad mē remittēbantur. Itaque trīstis eram ac miser. Parentēs meī multīs modīs mē dēlectāre cōnābantur, optimum cibum mihi dabant, sed ego paulum edēbam et nocte male dormiēbam.”\n\nCornēlius: “Cūr illa virgō pauper tē adulēscentem dīvitem nōn amābat?”\n\nIūlius: “Quia alium virum dīvitem amābat – nec vērō ab illō virō pessimō amābātur, quod virgō pauper erat!”\n\nCornēlius: “Quae erat illa virgō pauper?”\n\nIūlius: “Erat Aemilia, quae nunc uxor mea est ac mē nec ūllum alium virum amat. Hodiē beātī coniugēs sumus.”\n\nCornēlius: “Ego quoque adulēscēns virginem pauperem amābam, neque putābam mē ab eā amārī quia ipse pauper eram. Sed illa mē nec ūllum alium virum amābat – ac nunc uxor mea est. Nōs beātissimī sumus coniugēs, quamquam dīvitēs nōn sumus. Uxor mea mulier est optima ac pulcherrima.”\n\nIūlius: “Uxor tua nōn melior neque pulchrior est quam mea Aemilia!”"
 },
 {
  "id": "fab23",
  "cap": 20,
  "icon": "👶",
  "title": "Dē novō īnfante",
  "level": "cap. I–XX",
  "text": "Aemilia, quae iam duōs fīliōs et ūnam fīliam habet, novum īnfantem exspectat. Illa alteram fīliam habēre vult, sed marītus eius Iūlius magis gaudēbit sī fīlium habēbit, quamquam dīcit ‘sē velle fīliam habēre.’ Herī Iūlius nesciēbat uxōrem suam novum īnfantem exspectāre, quamquam vidēbat eam minus gracilem esse. Nunc autem intellegit Aemiliam nōn propter cibum crassiōrem ﬁerī!\n\nIūlia parentēs dē ‘alterā fīliā’ loquentēs audit, atque ita scit dē novō īnfante. Neque vērō gaudet Iūlia, nam sōla vult tōtum amōrem parentum sibi habēre! Verba Aemiliae dē parvulā sorōre quae aequē amābitur eam nōn satis cōnsōlantur.\n\nMārcus et Quīntus dē īnfante quī exspectātur nesciunt. Iūlia autem dē hāc rē tacēre nōn potest.\n\nFrātrēs vocat et iīs “Audīte!” inquit, “Mox ego nōn erō sōla puella cum duōbus puerīs.\n\nPost paucōs mēnsēs mihi soror erit.”\n\nPuerī statim ad mātrem adeunt eamque interrogant: “Estne vērum quod dīcit Iūlia? Sorōremne habēbimus?”\n\nAemilia: “Certē novum īnfantem habēbō, sed fīliumne an fīliam, nēmō scit. Vōsne frātrem an sorōrem habēre vultis? Nōnne laetābiminī sī alteram sorōrem habēbitis?”\n\nMārcus: “Ego parvulīs īnfantibus nōn dēlector. Semper in cūnīs iacent, mēcum lūdere nōn possunt, nihil dīcunt, sed magnā vōce vāgiunt!”\n\nAemilia: “Nōlī ita loquī, Mārce! Ante octō annōs tū ipse in cūnīs iacēbās ac vāgiēbās nec cum aliīs puerīs lūdere poterās.”\n\nQuīntus: “Ego nōn frātrem, sed sorōrem volō, etiam sī fīlia illa parvula sōla ā mātre cūrābitur, nōs līberī māiōrēs nōn cūrābimur!”\n\nAemilia: “Vōs omnēs bene cūrābiminī, etiam sī fīliolam habēbō. Nōlīte timēre!”"
 },
 {
  "id": "fab24",
  "cap": 20,
  "icon": "🧳",
  "title": "Fīlius mercātōris",
  "level": "cap. I–XX",
  "text": "Mīciō est mercātor quī Ōstiae prope portum habitat. Vir dīves est, quī mercēs suās, quae ex terrīs aliēnīs advehuntur, magnō pretiō in Italiā vēndit. Fīlius Mīciōnis, cui nōmen est Marīnus, iam adulēscēns est septendecim annōrum. Marīnus puer apud magistrum suum optimus discipulus erat, quī nōn modo litterās et numerōs bene discēbat, sed etiam ipse per sē librōs legēbat.\n\nMercātor sīc fīliō suō loquitur: “Ab hōc annō puer nōn es, Marīne. Volō tēcum loquī dē tempore futūrō. Vīsne mercātor esse ut pater tuus? an nauta?”\n\nMarīnus respondet: “Ego nec mercātor nec nauta esse volō, nam nōn sōlum nautae, sed etiam mercātōrēs nāvigāre dēbent, ac multae nāvēs cum mercibus in ﬂūctūs merguntur.\n\nTempestātēs et mare turbidum metuō. Sed nōlō domī manēre. In Graeciam ībō, quia litterās Graecās ac linguam Graecam discere volō. Doctus erō ut magister meus, nec sōlum librōs Latīnōs, sed etiam librōs Graecōs legam. In Graeciā virōs doctōs audīre poterō ac multās rēs ab optimīs magistrīs discere. Vīsne mē tēcum in Graeciam dūcere?”\n\nVerba fīliī patrem nōn dēlectant, nam is putābat fīlium suum velle mercātōrem esse. Nec tamen adulēscentem tam prūdentem domī tenēre vult, itaque fīliō “Gaudeō” inquit “quod vīs mēcum in Graeciam īre, quamquam mercātor esse nōn vīs. Bene intellegō tē, ut adulēscentem prūdentem, plūra discere velle in Graeciā apud magistrōs doctissimōs.\n\nSed nāvigāre necesse est, sī in Graeciam īre volumus, et tū dīcis ‘tē mare metuere neque nāvigāre velle’!”\n\nMarīnus: “Sī bonam nāvem et gubernātōrem prūdentem habēbimus ac ventum secundum, sine metū tēcum nāvigābō, pater.”\n\nSeptimō diē post hoc colloquium, ventō secundō atque caelō serēnō, Mīciō cum Marīnō fīliō proﬁcīscitur. In portū Ōstiēnsī fīlius mātrem suam complectitur et ōsculātur. “Valē, māter mea!” inquit, et māter lacrimam dētergēns “Ō Marīne! Vīve valēque!” Tum fīlius cum patre nāvem cōnscendit.\n\nVēla ventō implentur et nāvis plēnīs vēlīs ē portū ēgreditur."
 },
 {
  "id": "fab25",
  "cap": 20,
  "icon": "🚢",
  "title": "Gubernātor optimus",
  "level": "cap. I–XX",
  "text": "Mīciō mercātor cum fīliō suō Marīnō Graeciam petit. Mercēs suās magnō pretiō in Graeciā vēndere vult et illīc novās mercēs minōre pretiō emere, quās deinde in Italiā vēndet pretiō māiōre. Hōc modō mercātor prūdēns magnam pecūniam facere solet. Certē mercātor dīves est Mīciō.\n\nDum nāvis ventō secundō per mare vehitur, Marīnus in puppī sedet et librum dē optimō gubernātōre, cui nōmen erat Palinūrus, legere cōnātur. At diﬃcile est in puppī librum legere, quia gubernātor absentem cantat amīcam. Marīnus eum tacēre iubet, sed ille foedā vōce cantāre pergit!\n\nAdulēscēns oculōs ā librō suō tollēns mare et caelum intuētur. Suprā mare nūbēs ātrās orīrī videt et procul tonitrum audit. Statim patrem adit et “Vidēsne” inquit “illās nūbēs ātrās? Quid eās signiﬁcāre putās? Ego tonitrum ac tempestātem venientem timeō, nam tonitrus iam procul audītur. Nōlō in mediō marī tempestātem opperīrī. Iubē gubernātōrem portum petere, pater! Illīc fīnem tempestātis opperīrī poterimus.”\n\nMercātor vērō “Nōlī timēre!” inquit, “Gubernātor noster est bonus nauta, quī oﬃcium suum scit.\n\nCertē tū plūrēs librōs legis quam ille, et multās rēs diﬃcilēs scīs, sed nāvigāre nescīs – id librī tuī tē docēre nōn possunt. Manē tranquillus in puppī et perge librum tuum legere!” “Ego tranquillus sum” inquit fīlius, “nec iam tranquillum erit mare!”\n\nMarīnus ad gubernātōrem redit, quī māiōre vōce cantāre incipit, dum tōtum caelum nūbibus ātrīs operītur et iam prīma fulgura mare illūstrant. Gubernātor vērō neque caelum neque mare aspicit, et male canere pergit! “Tacē, gubernātor!” inquit adulēscēns, “Spectā caelum! Fac oﬃcium tuum! Necesse est portum petere, antequam māxima tempestās oritur.”\n\nGubernātor nūllum verbum respondet, sed rīdēns sē ad Marīnum vertit eumque ūmidīs oculīs intuētur. Tum adulēscēns animadvertit eum manū tenēre pōculum – ex quō nōn aquam bibit!\n\nSubitō magnus ventus ﬂāre incipit ac nāvis magnīs ﬂūctibus iactātur. Gubernātor surgere cōnātur nec pedibus stāre potest et ante Marīnum lābitur. Clāmant omnēs et Neptūnum invocant: “Servā nōs, Neptūne!” Nāvis sine gubernātōre in marī turbidō errat atque aquā implērī incipit. Nautae aquam haurīre cōnantur ac mercēs gravēs in mare iaciunt.\n\nTum vērō, omnibus perterritīs, Marīnus tranquillus in locō gubernātōris cōnsīdit: is nāvem contrā ventum vertit et in mediīs ﬂūctibus rēctē gubernat. Ita nāvis servātur nec ﬂūctibus mergitur. Paulō post ventus cadere incipit.\n\nLaetantur omnēs et Marīnum ut optimum gubernātōrem laudant eumque ‘alterum Palinūrum’ vocant.\n\nMīciō laetus fīlium complectitur et “Profectō” inquit “tū nōn sōlum librōs legere, sed etiam nāvem gubernāre scīs!”\n\nMarīnus autem “Librum legēbam” inquit “dē Palinūrō, optimō gubernātōre. Ut vidēs, librī meī multās rēs mē docēre possunt.”"
 },
 {
  "id": "fab26",
  "cap": 21,
  "icon": "📏",
  "title": "Magister numerōs dictat",
  "level": "cap. I–XXI",
  "text": "Magister Diodōrus, postquam discipulōs numerōs breviter scrībere docuit, sex numerōs iīs dictat: ‘quattuor’, ‘novem’, ‘quattuordecim’, ‘ūndēvīgintī’, ‘quadringenta’, ‘nōngenta’. Cūr magister ‘quadringenta’ et ‘nōngenta’ dīcit, nōn ‘quadringentī’ et nōngentī’? Numerī quī in -genta dēsinunt sunt neutrum plūrālis.\n\nQuisque discipulus suō modō numerōs scrībit. Sextus sīc scrībit: IV, IX, XI, XIX, CD, CM; Titus sīc: IV, IX, XIV, XIX, XL, XC; Mārcus sīc: IIII, VIIII, XIIII, XVIIII, CCCC, DCCCC.\n\nDiodōrus, postquam numerōs dictāvit et discipulī eōs scrīpsērunt, tabulam cuiusque discipulī in manūs sūmit et spectat id quod scrīptum est. Nēmō discipulus omnēs numerōs rēctē scrīpsit, at magister Sextum et Titum quattuor numerōs rēctē scrīpsisse videt. “Vōs” inquit “quattuor numerōs rēctē scrīpsistis, Sexte et Tite.”\n\nSextus: “Scrīpsimus ita ut nōs numerōs scrībere docuistī.”\n\nDiodōrus: “Nec vērō tē CD et CM scrībere docuī, Sexte, nam C rārō pōnitur ante D et M, ‘quadringenta’ et ‘nōngenta’ rēctius scrībuntur CCCC et DCCCC.”\n\nMārcus: “Ego ita scrīpsī!” Mārcus dīcit ‘sē ita scrīpsisse’\n\nMagister: “Tū rēctē C quater scrīpsistī in iīs numerīs, sed etiam I quater scrīpsistī in numerīs ‘quattuor’, ‘novem’, ‘quattuordecim’, ‘ūndēvīgintī’: IIII, VIIII, XIIII, XVIIII. Id tē nōn docuī! Sciō antīquōs Rōmānōs totiēs I scrīpsisse, sed hodiē littera I pōnitur ante V et X: ‘quattuor’ scrībitur IV, ‘novem’ IX, ‘quattuordecim’ XIV, ‘ūndēvīgintī’ XIX – hī numerī rēctē scrīptī sunt ā Sextō et Titō.” Magister dīcit ‘hōs numerōs ā Sextō et Titō rectē scrīptōs esse.’ Tum magister sē vertit ad Titum, quī XL et XC scrīpsit, et “Sed cūr tū” inquit “XL et XC scrīpsistī? Eae litterae signiﬁcant ‘quadrāgintā et ‘nōnāgintā’, nōn ‘quadringenta’ et ‘nōngenta’, ut ego vōbīs dictāvī.”\n\nTitus: “Ego tē ‘quadrāgintā’ et ‘nōnāgintā’ dīcere audīvī.”\n\nMagister: “Male audīvistī! Tūne malās aurēs habēs? Profectō ‘quadringenta’ et ‘nōngenta’ dīxī. Nōnne vōs mē ita dīcere audīvistis, Mārce et Sexte?”\n\nSextus: “Certē nōs ita tē dīcere audīvimus. Scrīpsimus eōs numerōs quōs nōbīs dictāvistī.” Sextus et Mārcus magistrum numerōs ‘quadringenta’ et ‘nōngenta’ dictantem bene audīvērunt, Titus male audīvit.\n\nMārcus: “Sed ego ūnus ex tribus discipulīs eōs numerōs rēctē scrīpsī! Cūr mē nōn laudāvistī, magister?”\n\nMagister: “Tē nōn laudāvī, quia aliōs quattuor numerōs prāvē scrīpsistī.”\n\nMārcus: “Ego scrīpsī ut antīquī Rōmānī scrībēbant. Num tū antīquōs Rōmānōs prāvē scrīpsisse putās?”"
 },
 {
  "id": "fab27",
  "cap": 22,
  "icon": "🚪",
  "title": "Iānitor probus",
  "level": "cap. I–XXII",
  "text": "Dōrippa, amīca Lÿdiae, sōla habitat Rōmae in domō apud Tiberim ﬂūmen. Forēs domūs cūstōdit iānitor, cui nōmen est Sanniō.\n\nDōrippa Lepidum amīcum habēbat, sed iam eum ē domō suā pepulit, quia eum falsum amīcum esse arbitrātur.\n\nDomum reversus Dōrippa iānitōrī “Sī Lepidus redit” inquit, “nōlī admittere eum! Virum illum improbum iam vidēre nōlō. Nōn mē, sed ancillam amat.”\n\nVesperī Lepidus cum novīs ﬂōribus redit atque iānuam pulsat clāmāns: “Heus, iānitor! Aperī iānuam! Lepidus sum. Veniō amīcam meam salūtātum.”\n\nSanniō: “Nōn licet mihi tē admittere. Dōrippa tēcum colloquī nōn vult. Putō eam iam dormītum iisse. Dīcit ‘nōn sē, sed aliam fēminam ā tē amārī’.”\n\nLepidus: “Nōn vērum est quod illa dīcit. Ego sum vērus amīcus quī amīcam meam nōn fallō.\n\nNecesse mihi est cum eā colloquī.”\n\nSanniō: “Sed Dōrippa mē iubet tibi iānuam claudere.”\n\nLepidus: “Nōn oportet illī fēminae sevērae pārēre! Iam aperī iānuam!”\n\nSanniō: “Profectō dominae meae pārēbō. Tē nōn admittō.”\n\nLepidus dēnārium prōmit et iānitōrī ostendit: “Ecce dēnārius” inquit, “sī iānuam mihi aperīs, dēnārium tibi dō.”\n\nSanniō: “Quamquam pauper sum, istam pecūniam ā tē accipere nōlō. Ego dominam meam nōn fallō!”\n\nTandem Lepidus intellegit sē iānitōrem probum nūllō modō movēre posse. Flōrēs ante forēs iaciēns “Valē” inquit, “iānitor – dūrior quam forēs tuae!”"
 },
 {
  "id": "fab28",
  "cap": 23,
  "icon": "🤝",
  "title": "Neuter recēdere vult",
  "level": "cap. I–XXIII",
  "text": "Lēander, servus Iūliī, postquam in forō Tūsculānō piscēs et ōva ēmit, viam angustam intrat quae ā forō ad portam oppidī dūcit. In eā viā dominō Cornēliō occurrit, quī equō vehitur ad forum. Lēander ipse ā forō vehitur asinō. Necesse est utrumque cōnsistere, nam nimis angusta est via. Sed neuter eōrum, nec dominus nec servus, recēdere vult.\n\nCornēlius vultū sevērō servum aspiciēns “Heus tū, serve!” inquit, “Cēde mihi! Iubē asinum tuum ad forum revertī!”\n\nAd hoc Lēander, quī scit asinum suum pāritūrum nōn esse, “Asinus meus” inquit “mihi hoc iubentī nōn pārēbit. Prōcēdere vult, recēdere nōn vult! Atque ego iam procul absum ā forō. Tū redī ad portam!”\n\nAt dominus īrātus “Profectō” inquit “nōlō tibi, sordidō servō, cēdere! Nisi tū mihi cēdis, hōc baculō tē et asinum tuum verberātūrus sum!” Cornēlius dīcit ‘sē servum et asinum eius verberātūrum esse’ ac sōlus adversus Lēandrum accēdit baculum ante sē tenēns.\n\nTum vērō asinus rudere incipit: “Hīaāhīaā...!” Turpissimā asinī vōce territus equus in pedēs posteriōrēs surgēns sē vertit atque ē locō fugit. Asinus cum Lēandrō equum currentem sequitur neque Cornēlius eum retinēre potest.\n\nRubēns ob pudōrem Cornēlius redit ad equum suum, quī intrā portam dominum exspectat."
 },
 {
  "id": "fab29",
  "cap": 24,
  "icon": "🏠",
  "title": "Redit Sextus",
  "level": "cap. I–XXIV",
  "text": "Hōra septima est. Eā hōrā Cornēlius ambulātum īre solet antequam lavātum it, sed hodiē propter imbrem et tonitrum ambulāre nōn potest. Domī manet apud uxōrem suam Fabiam, quae in ātriō Sextum fīlium exspectat.\n\nFabia: “Sextus ante hōram septimam redīre solet. Quid eum agere putās?”\n\nCornēlius: “Per hunc imbrem ac tonitrum ambulāre nōn potest. Putō eum sub tēctō exspectāre dum tonitrus dēsinet.”\n\nTandem iānua aperītur et Sextus ātrium intrat. Parentēs vērō fīlium suum vix cognōscunt, nam faciēs puerī cruenta est atque vestis eius sordida. “Salvēte, pater et māter!” inquit puer. “Ō mī fīlī!” inquit māter cruōrem cōnspiciēns, “Quid tibi factum est?”\n\nSextus: “Pugnāvī cum Mārcō et Titō. Iī mē pulsāvērunt, postquam ego Mārcum pulsāvī.”\n\nFabia: “Cūr tū Mārcum pulsāvistī?\n\nSextus: “Quia ille dīxerat ‘mātrem meam fēminam turpem esse!’’\n\nCornēlius : “Quid? Itane dīxit ille puer improbus?”\n\nSextus: “Nōn iīs ipsīs verbīs. Dīxit ‘suam mātrem fōrmōsissimam esse’ ac ‘mātrem meam sine ōrnāmentīs fōrmōsam nōn esse.’ Posteā mē ‘puerum barbarum’ vocāvit, quod eum pulsāveram.”\n\nCornēlius: “Profectō nōn sine causā Mārcum pulsāvistī, quia mātrī tuae male dīxerat! Nam māter tua fōrmōsior est quam māter Mārcī, etiam sī illa plūra et pulchriōra ōrnāmenta habet.\n\nNec tū puer barbarus es, sed doctior Mārcō.”\n\nSextus: “Certē nōn tam indoctus sum quam ille: rēctius et pulchrius scrībō ac melius computō.\n\nMagister mē laudāvit quod rēctissimē et pulcherrimē scrīpseram atque etiam assem mihi dedit quod optimē computāveram.” Sextus assem prōmit et parentibus ostendit.\n\nFabia: “Gaudēmus tē optimum discipulum esse. Nōn modo laudem, sed etiam dōnum meruistī.\n\nOstende nōbīs litterās tuās quae laudātae sunt ā magistrō!”\n\nSextus prōmit tabellam, quam suam esse putābat, eamque parentibus ostendit.\n\nCornēlius tabellam spectāns mīrātur litterās foedās ac diﬃcilēs lēctū esse. “Quidnam hoc est?” inquit, “Num magister hās litterās laudāvit?”\n\nSextus: “Immō ‘litterās foedās esse’ dīxit, sed hae litterae ā Mārcō scrīptae sunt. Iam intellegō Mārcum tabulās nostrās mūtāvisse inter pugnam. Is meam tabulam sūmpsit – mīror eum assem meum nōn sūmpsisse!”\n\nFabia: “Mārcus multōs nummōs ā patre suō dīvite accipit.”\n\nSextus: “Rēctē dīcis: is multōs nummōs habet – ac nescit numerāre pecūniam suam! Ego ūnum assem habeō ac sciō quattuor assēs facere sēstertium et quattuor sēstertiōs dēnārium.”\n\nCornēlius: “Quot assēs faciunt quattuor sēstertiī?”\n\nSextus: “Sēdecim scīlicet. Hoc idem magister nōs interrogāvit. Sed id quod mē interrogāvit multō diﬃcilius erat. Ecce exemplum: Quot dēnāriōs faciunt duodēquīnquāgintā sēstertiī? Tū mihi respondē, pater!”"
 },
 {
  "id": "fab30",
  "cap": 25,
  "icon": "🗣️",
  "title": "Puer barbarus",
  "level": "cap. I–XXV",
  "text": "Prīmā lūce Mārcus cum Dāvō Tūsculum ambulat. Dāvus nōn modo rēs Mārcī fert, sed etiam epistulam quam Iūlius ad magistrum scrīpsit.\n\nDāvus: “Ecce epistulam dominī ferō, quam tū ipse magistrō tuō trādēs.”\n\nMārcus: “Etiamne mercēdem fers, quam magistrō dēbēmus?”\n\nDāvus: “Pecūniam nōn ferō. Pater tuus mercēdem solvere nōn vult.”\n\nMārcus: “Ergō magister īrātus erit mihi.”\n\nDāvus: “Nōn tibi, sed patrī tuō īrātus erit. Dominus enim plānē scrībit ‘magistrum nihil tē docēre posse neque igitur mercēdem meruisse!’”\n\nMārcus: “Ita est ut scrībit pater: nihil discō ab illō magistrō!”\n\nMārcus et Dāvus incipiunt montem ascendere in quō situm est Tūsculum.\n\nMārcus: “Mīror quod oppidum nōn in valle, sed in monte situm est.”\n\nDāvus: “Oppida in montibus aediﬁcantur, quia facilius est montem dēfendere. Diﬃcile enim est hostibus montem ascendere.”\n\nMārcus frontem tergēns “Nōn sōlum hostibus” inquit “diﬃcile est. Ego semper fessus sum cum tandem ad lūdum advēnī. Ob eam causam necesse est in lūdō dormīre!”\n\nDāvus: “Id tē nōn excūsat. Posthāc necesse erit tē in lūdō vigilāre ac magistrō pārēre. Laetāre quod tibi licet in lūdum īre – mihi puerō nōn licēbat.”\n\nMārcus: “Sed tū servus es, Dāve.”\n\nDāvus: “In patriā meā servus nōn eram. Patria mea est Britannia.”\n\nMārcus: “Ergō puer barbarus erās.”\n\nDāvus: “Laetāre quod tū puer barbarus nōn es! Puerīs barbarīs nōn licet litterās et numerōs discere.”\n\nMārcus: “At puerīs barbarīs licet diēs tōtōs cum aliīs puerīs lūdere, per campōs et silvās errāre, in ﬂūminibus natāre, equōs regere, ferās occīdere, nec iīs necesse est ante lūcem surgere.”\n\nDāvus: “Puerī barbarī nōn tam beātē vīvunt quam tū putās. Multa mihi puerō erant oﬃcia, nec enim servum nec ancillam habēbat pater meus.”\n\nMārcus: “Quārē ex patriā tuā profectus es?”\n\nDāvus: “Parentēs meī ā mīlitibus Rōmānīs necātī sunt, quia Rōmānīs auxilium ferre nōlēbant.”\n\nMārcus: “Cūr Rōmānīs auxilium negābant?”\n\nMārcus: “Quia Rōmānī hostēs erant Britannōrum. Ego cum parentibus meīs habitābam in parvā domō apud magnam silvam in quā exercitus Britannōrum sē occultābat. Subitō mīlitēs Rōmānī domum nostram intrāvērunt ac patrem meum interrogāre coepērunt. Ille vērō cīvēs suōs, quī patriam suam ab hostibus Rōmānīs dēfendēbant, fallere nōlēbat neque ūllum verbum fēcit dē exercitū Britannōrum quī in silvīs occultābātur. Meīs oculīs vīdī patrem et mātrem ā saevīs mīlitibus occīdī. Ipse puer quīndecim annōrum cum cēterīs Britannīs captīs Rōmam missus sum et servus factus. Pater Iūliī mē sescentīs sēstertiīs ēmit.”"
 }
]));
